// package music;

// import org.junit.jupiter.api.BeforeEach;
// import org.junit.jupiter.api.Test;
// import music.playlist.domain.Playlist;
// import music.playlist.repository.InMemoryPlaylistRepository;
// import music.playlist.service.PlaylistService;
// import static org.junit.jupiter.api.Assertions.*;
// import java.util.HashSet;


// //NOTE: THEY ARE GENERATED BY COPILOT AGENT
// class PlaylistServiceTest {

//     // ── In-memory stub repository ────────────────────────────────────────────────

//     private PlaylistService playlistService;

//     @BeforeEach
//     void setUp() {
//         playlistService = new PlaylistService(new InMemoryPlaylistRepository());
//     }

//     // ── createPlaylist(String) ───────────────────────────────────────────────────

//     @Test
//     void createPlaylist_withName_returnsPlaylistWithCorrectName() {
//         Playlist result = playlistService.createPlaylist("My Playlist");

//         assertNotNull(result);
//         assertEquals("My Playlist", result.getPlaylistName());
//     }

//     @Test
//     void createPlaylist_withName_generatesNonNullId() {
//         Playlist result = playlistService.createPlaylist("My Playlist");

//         assertNotNull(result.getPlaylistId());
//         assertFalse(result.getPlaylistId().isBlank());
//     }

//     @Test
//     void createPlaylist_withName_twoCallsProduceUniqueIds() {
//         Playlist p1 = playlistService.createPlaylist("Playlist 1");
//         Playlist p2 = playlistService.createPlaylist("Playlist 2");

//         assertNotEquals(p1.getPlaylistId(), p2.getPlaylistId());
//     }

//     // ── createPlaylist() (no-arg) ────────────────────────────────────────────────

//     @Test
//     void createPlaylist_noArg_returnsPlaylistWithDefaultName() {
//         Playlist result = playlistService.createPlaylist();

//         assertNotNull(result);
//         assertEquals("Untitle", result.getPlaylistName());
//     }

//     @Test
//     void createPlaylist_noArg_generatesNonNullId() {
//         Playlist result = playlistService.createPlaylist();

//         assertNotNull(result.getPlaylistId());
//         assertFalse(result.getPlaylistId().isBlank());
//     }

//     // ── getPlaylistById ──────────────────────────────────────────────────────────

//     @Test
//     void getPlaylistById_existingId_returnsPlaylist() {
//         Playlist created = playlistService.createPlaylist("Test");

//         Playlist result = playlistService.getPlaylistById(created.getPlaylistId());

//         assertNotNull(result);
//         assertEquals(created.getPlaylistId(), result.getPlaylistId());
//     }

//     @Test
//     void getPlaylistById_nonExistingId_returnsNull() {
//         Playlist result = playlistService.getPlaylistById("non-existing-id");

//         assertNull(result);
//     }

//     // ── renamePlaylist ───────────────────────────────────────────────────────────

//     @Test
//     void renamePlaylist_existingPlaylist_updatesName() {
//         Playlist created = playlistService.createPlaylist("Old Name");

//         playlistService.renamePlaylist(created.getPlaylistId(), "New Name");

//         Playlist result = playlistService.getPlaylistById(created.getPlaylistId());
//         assertEquals("New Name", result.getPlaylistName());
//     }

//     @Test
//     void renamePlaylist_nonExistingPlaylist_doesNotThrow() {
//         assertDoesNotThrow(() ->
//                 playlistService.renamePlaylist("non-existing-id", "New Name"));
//     }

//     // ── deletePlaylist ───────────────────────────────────────────────────────────

//     @Test
//     void deletePlaylist_existingPlaylist_removesIt() {
//         Playlist created = playlistService.createPlaylist("To Delete");

//         playlistService.deletePlaylist(created.getPlaylistId());

//         assertNull(playlistService.getPlaylistById(created.getPlaylistId()));
//     }

//     @Test
//     void deletePlaylist_nonExistingPlaylist_doesNotThrow() {
//         assertDoesNotThrow(() ->
//                 playlistService.deletePlaylist("non-existing-id"));
//     }

//     // ── addTrack ─────────────────────────────────────────────────────────────────

//     @Test
//     void addTrack_existingPlaylist_addsTrackId() {
//         Playlist created = playlistService.createPlaylist("Playlist");

//         playlistService.addTrack(created.getPlaylistId(), "track-1");

//         HashSet<String> trackIds = playlistService.loadTrackIds(created.getPlaylistId());
//         assertTrue(trackIds.contains("track-1"));
//     }

//     @Test
//     void addTrack_duplicateTrackId_isStoredOnce() {
//         Playlist created = playlistService.createPlaylist("Playlist");

//         playlistService.addTrack(created.getPlaylistId(), "track-1");
//         // System.out.println("Tracks in Playlist"+playlistService.getPlaylistById(created.getPlaylistId()).getTrackIds());
//         playlistService.addTrack(created.getPlaylistId(), "track-1");

//         HashSet<String> trackIds = playlistService.loadTrackIds(created.getPlaylistId());
//         assertEquals(1, trackIds.size());
//     }

//     @Test
//     void addTrack_multipleTrackIds_allAdded() {
//         Playlist created = playlistService.createPlaylist("Playlist");

//         playlistService.addTrack(created.getPlaylistId(), "track-1");
//         playlistService.addTrack(created.getPlaylistId(), "track-2");
//         playlistService.addTrack(created.getPlaylistId(), "track-3");

//         HashSet<String> trackIds = playlistService.loadTrackIds(created.getPlaylistId());
//         assertEquals(3, trackIds.size());
//         assertTrue(trackIds.contains("track-1"));
//         assertTrue(trackIds.contains("track-2"));
//         assertTrue(trackIds.contains("track-3"));
//     }

//     @Test
//     void addTrack_nonExistingPlaylist_doesNotThrow() {
//         assertDoesNotThrow(() ->
//                 playlistService.addTrack("non-existing-id", "track-1"));
//     }

//     // ── removeTrack ──────────────────────────────────────────────────────────────

//     @Test
//     void removeTrack_existingTrack_removesIt() {
//         Playlist created = playlistService.createPlaylist("Playlist");
//         playlistService.addTrack(created.getPlaylistId(), "track-1");

//         playlistService.removeTrack(created.getPlaylistId(), "track-1");

//         HashSet<String> trackIds = playlistService.loadTrackIds(created.getPlaylistId());
//         assertFalse(trackIds.contains("track-1"));
//     }

//     @Test
//     void removeTrack_nonExistingTrack_doesNotThrow() {
//         Playlist created = playlistService.createPlaylist("Playlist");

//         assertDoesNotThrow(() ->
//                 playlistService.removeTrack(created.getPlaylistId(), "non-existing-track"));
//     }

//     @Test
//     void removeTrack_nonExistingPlaylist_doesNotThrow() {
//         assertDoesNotThrow(() ->
//                 playlistService.removeTrack("non-existing-id", "track-1"));
//     }

//     @Test
//     void removeTrack_removesOnlyTargetTrack() {
//         Playlist created = playlistService.createPlaylist("Playlist");
//         playlistService.addTrack(created.getPlaylistId(), "track-1");
//         playlistService.addTrack(created.getPlaylistId(), "track-2");

//         playlistService.removeTrack(created.getPlaylistId(), "track-1");

//         HashSet<String> trackIds = playlistService.loadTrackIds(created.getPlaylistId());
//         assertFalse(trackIds.contains("track-1"));
//         assertTrue(trackIds.contains("track-2"));
//     }

//     // ── loadTrackIds ─────────────────────────────────────────────────────────────

//     @Test
//     void loadTrackIds_existingPlaylist_returnsTrackIds() {
//         Playlist created = playlistService.createPlaylist("Playlist");
//         playlistService.addTrack(created.getPlaylistId(), "track-1");

//         HashSet<String> result = playlistService.loadTrackIds(created.getPlaylistId());

//         assertNotNull(result);
//         assertTrue(result.contains("track-1"));
//     }

//     @Test
//     void loadTrackIds_emptyPlaylist_returnsEmptySet() {
//         Playlist created = playlistService.createPlaylist("Playlist");

//         HashSet<String> result = playlistService.loadTrackIds(created.getPlaylistId());

//         assertNotNull(result);
//         assertTrue(result.isEmpty());
//     }

//     @Test
//     void loadTrackIds_nonExistingPlaylist_returnsNull() {
//         HashSet<String> result = playlistService.loadTrackIds("non-existing-id");

//         assertNull(result);
//     }
// }
