package music;

import music.player.domain.PlayerCommand;
import music.player.domain.PlayerState;
import music.player.dto.PlayerCommandDTO;
import music.player.repository.InMemoryPlayerRepository;
import music.player.repository.PlayerRepository;
import music.player.service.PlayerService;
import music.player.domain.PlayerStatus;
import music.player.domain.RepeatMode;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertSame;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertThrows;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;

import java.util.ArrayList;
import java.util.List;


//NOTE: ALL TESTS ARE GENERATED BY AI COPILOT;
class PlayerServiceTest {

    private PlayerService playerService;
    private PlayerRepository repository;

    @BeforeEach
    void setUp() {
        repository = new InMemoryPlayerRepository();
        playerService = new PlayerService(repository);
    }

    // ── getPlayerState ──────────────────────────────────────────────────────────

    @Test
    void getPlayerState_userDoesNotExist_returnsNull() {
        PlayerState result = playerService.getPlayerState("u1");
        assertNull(result);
    }

    @Test
    void getPlayerState_userExists_returnsState() {
        PlayerState state = new PlayerState();
        state.setUserId("u1");
        repository.savePlayerState(state);

        PlayerState result = playerService.getPlayerState("u1");
        assertNotNull(result);
        assertSame(state, result);
    }

    // ── removeUser ──────────────────────────────────────────────────────────────

    @Test
    void removeUser_userExists_removesFromRepository() {
        PlayerState state = new PlayerState();
        state.setUserId("u1");
        repository.savePlayerState(state);

        playerService.removeUser("u1");

        assertNull(playerService.getPlayerState("u1"));
        assertTrue(repository.findAllPlayerStates().isEmpty());
    }

    @Test
    void removeUser_userDoesNotExist_doesNotThrow() {
        playerService.removeUser("nonexistent");
        assertTrue(repository.findAllPlayerStates().isEmpty());
    }

    // ── applyCommand: PLAY / PAUSE ──────────────────────────────────────────────

    @Test
    void applyCommand_playCommand_setsStatusPlaying() {
        PlayerState state = new PlayerState();
        state.setUserId("u1");
        state.setStatus(PlayerStatus.PAUSED);
        repository.savePlayerState(state);

        PlayerCommandDTO cmd = buildCommand("u1", PlayerCommand.PLAY);
        PlayerState result = playerService.applyCommand(cmd);

        assertEquals(PlayerStatus.PLAYING, result.getStatus());
    }

    @Test
    void applyCommand_pauseCommand_setsStatusPaused() {
        PlayerState state = new PlayerState();
        state.setUserId("u1");
        state.setStatus(PlayerStatus.PLAYING);
        repository.savePlayerState(state);

        PlayerCommandDTO cmd = buildCommand("u1", PlayerCommand.PAUSE);
        PlayerState result = playerService.applyCommand(cmd);

        assertEquals(PlayerStatus.PAUSED, result.getStatus());
    }

    // ── applyCommand: new user auto-created ────────────────────────────────────

    @Test
    void applyCommand_newUser_createsStateAndAppliesCommand() {
        PlayerCommandDTO cmd = buildCommand("newUser", PlayerCommand.PLAY);
        PlayerState result = playerService.applyCommand(cmd);

        assertNotNull(result);
        assertEquals("newUser", result.getUserId());
        assertEquals(PlayerStatus.PLAYING, result.getStatus());
    }

    // ── applyCommand: RESTART ───────────────────────────────────────────────────

    @Test
    void applyCommand_restartCommand_setsPositionToZero() {
        PlayerState state = new PlayerState();
        state.setUserId("u1");
        state.setPosition(120);
        repository.savePlayerState(state);

        PlayerCommandDTO cmd = buildCommand("u1", PlayerCommand.RESTART);
        PlayerState result = playerService.applyCommand(cmd);

        assertEquals(0, result.getPosition());
    }

    // ── applyCommand: SEEK_FORWARD ──────────────────────────────────────────────

    @Test
    void applyCommand_seekForward_increasesPosition() {
        PlayerState state = new PlayerState();
        state.setUserId("u1");
        state.setPosition(10);
        state.setDuration(100);
        repository.savePlayerState(state);

        PlayerCommandDTO cmd = buildCommand("u1", PlayerCommand.SEEK_FORWARD);
        cmd.setPosition(20);
        PlayerState result = playerService.applyCommand(cmd);

        assertEquals(30, result.getPosition());
    }

    @Test
    void applyCommand_seekForward_clampsToDuration() {
        PlayerState state = new PlayerState();
        state.setUserId("u1");
        state.setPosition(90);
        state.setDuration(100);
        repository.savePlayerState(state);

        PlayerCommandDTO cmd = buildCommand("u1", PlayerCommand.SEEK_FORWARD);
        cmd.setPosition(50);
        PlayerState result = playerService.applyCommand(cmd);

        assertEquals(100, result.getPosition());
    }

    @Test
    void applyCommand_seekForward_nullPosition_throwsIllegalArgument() {
        PlayerState state = new PlayerState();
        state.setUserId("u1");
        state.setPosition(10);
        state.setDuration(100);
        repository.savePlayerState(state);

        PlayerCommandDTO cmd = buildCommand("u1", PlayerCommand.SEEK_FORWARD);
        // position intentionally left null

        assertThrows(IllegalArgumentException.class, () -> playerService.applyCommand(cmd));
    }

    // ── applyCommand: SEEK_BACKWARD ─────────────────────────────────────────────

    @Test
    void applyCommand_seekBackward_decreasesPosition() {
        PlayerState state = new PlayerState();
        state.setUserId("u1");
        state.setPosition(50);
        state.setDuration(100);
        repository.savePlayerState(state);

        PlayerCommandDTO cmd = buildCommand("u1", PlayerCommand.SEEK_BACKWARD);
        cmd.setPosition(20);
        PlayerState result = playerService.applyCommand(cmd);

        assertEquals(30, result.getPosition());
    }

    @Test
    void applyCommand_seekBackward_clampsToZero() {
        PlayerState state = new PlayerState();
        state.setUserId("u1");
        state.setPosition(10);
        state.setDuration(100);
        repository.savePlayerState(state);

        PlayerCommandDTO cmd = buildCommand("u1", PlayerCommand.SEEK_BACKWARD);
        cmd.setPosition(50);
        PlayerState result = playerService.applyCommand(cmd);

        assertEquals(0, result.getPosition());
    }

    @Test
    void applyCommand_seekBackward_nullPosition_throwsIllegalArgument() {
        PlayerState state = new PlayerState();
        state.setUserId("u1");
        state.setPosition(10);
        state.setDuration(100);
        repository.savePlayerState(state);

        PlayerCommandDTO cmd = buildCommand("u1", PlayerCommand.SEEK_BACKWARD);

        assertThrows(IllegalArgumentException.class, () -> playerService.applyCommand(cmd));
    }

    // ── applyCommand: NEXT ──────────────────────────────────────────────────────

    @Test
    void applyCommand_nextCommand_advancesTrackIndex() {
        PlayerState state = buildStateWithTracks("u1", 3);
        state.setCurrentTrackIndex(0);
        state.setRepeatMode(RepeatMode.OFF);
        repository.savePlayerState(state);

        PlayerCommandDTO cmd = buildCommand("u1", PlayerCommand.NEXT);
        PlayerState result = playerService.applyCommand(cmd);

        assertEquals(1, result.getCurrentTrackIndex());
        assertEquals(PlayerStatus.PLAYING, result.getStatus());
    }

    @Test
    void applyCommand_nextCommand_atLastTrack_repeatOff_doesNotAdvance() {
        PlayerState state = buildStateWithTracks("u1", 3);
        state.setCurrentTrackIndex(2);
        state.setRepeatMode(RepeatMode.OFF);
        repository.savePlayerState(state);

        PlayerCommandDTO cmd = buildCommand("u1", PlayerCommand.NEXT);
        PlayerState result = playerService.applyCommand(cmd);

        assertEquals(2, result.getCurrentTrackIndex());
    }

    @Test
    void applyCommand_nextCommand_atLastTrack_repeatAll_wrapsToFirst() {
        PlayerState state = buildStateWithTracks("u1", 3);
        state.setCurrentTrackIndex(2);
        state.setRepeatMode(RepeatMode.ALL);
        repository.savePlayerState(state);

        PlayerCommandDTO cmd = buildCommand("u1", PlayerCommand.NEXT);
        PlayerState result = playerService.applyCommand(cmd);

        assertEquals(0, result.getCurrentTrackIndex());
    }

    @Test
    void applyCommand_nextCommand_repeatOne_restartsCurrentTrack() {
        PlayerState state = buildStateWithTracks("u1", 3);
        state.setCurrentTrackIndex(1);
        state.setPosition(50);
        state.setRepeatMode(RepeatMode.ONE);
        repository.savePlayerState(state);

        PlayerCommandDTO cmd = buildCommand("u1", PlayerCommand.NEXT);
        PlayerState result = playerService.applyCommand(cmd);

        assertEquals(1, result.getCurrentTrackIndex());
        assertEquals(0, result.getPosition());
        assertEquals(PlayerStatus.PLAYING, result.getStatus());
    }

    // ── applyCommand: PREVIOUS ──────────────────────────────────────────────────

    @Test
    void applyCommand_previousCommand_goesToPreviousTrack() {
        PlayerState state = buildStateWithTracks("u1", 3);
        state.setCurrentTrackIndex(2);
        state.setRepeatMode(RepeatMode.OFF);
        repository.savePlayerState(state);

        PlayerCommandDTO cmd = buildCommand("u1", PlayerCommand.PREVIOUS);
        PlayerState result = playerService.applyCommand(cmd);

        assertEquals(1, result.getCurrentTrackIndex());
        assertEquals(PlayerStatus.PLAYING, result.getStatus());
    }

    @Test
    void applyCommand_previousCommand_atFirstTrack_repeatOff_doesNotGoBack() {
        PlayerState state = buildStateWithTracks("u1", 3);
        state.setCurrentTrackIndex(0);
        state.setRepeatMode(RepeatMode.OFF);
        repository.savePlayerState(state);

        PlayerCommandDTO cmd = buildCommand("u1", PlayerCommand.PREVIOUS);
        PlayerState result = playerService.applyCommand(cmd);

        assertEquals(0, result.getCurrentTrackIndex());
    }

    @Test
    void applyCommand_previousCommand_atFirstTrack_repeatAll_wrapsToLast() {
        PlayerState state = buildStateWithTracks("u1", 3);
        state.setCurrentTrackIndex(0);
        state.setRepeatMode(RepeatMode.ALL);
        repository.savePlayerState(state);

        PlayerCommandDTO cmd = buildCommand("u1", PlayerCommand.PREVIOUS);
        PlayerState result = playerService.applyCommand(cmd);

        assertEquals(2, result.getCurrentTrackIndex());
    }

    // ── applyCommand: SHUFFLE_TOGGLE ────────────────────────────────────────────

    @Test
    void applyCommand_shuffleToggle_enablesShuffle() {
        PlayerState state = buildStateWithTracks("u1", 3);
        state.setShuffle(false);
        repository.savePlayerState(state);

        PlayerCommandDTO cmd = buildCommand("u1", PlayerCommand.SHUFFLE_TOGGLE);
        PlayerState result = playerService.applyCommand(cmd);

        assertTrue(result.isShuffle());
        assertNotNull(result.getShuffledOrder());
        assertEquals(3, result.getShuffledOrder().size());
    }

    @Test
    void applyCommand_shuffleToggle_disablesShuffle() {
        PlayerState state = buildStateWithTracks("u1", 3);
        state.setShuffle(false);
        repository.savePlayerState(state);

        // enable first so shuffled order is populated
        playerService.applyCommand(buildCommand("u1", PlayerCommand.SHUFFLE_TOGGLE));
        System.out.println("Before toggle:"+playerService.getPlayerState("u1").isShuffle());
        // now disable
        PlayerState result = playerService.applyCommand(buildCommand("u1", PlayerCommand.SHUFFLE_TOGGLE));
        System.out.println("After toggle: "+playerService.getPlayerState("u1").isShuffle());
        assertFalse(result.isShuffle());
        assertNull(result.getShuffledOrder());
    }

    // ── applyCommand: REPEAT_TOGGLE ─────────────────────────────────────────────

    @Test
    void applyCommand_repeatToggle_cyclesOff_to_All_to_One_to_Off() {
        PlayerState state = new PlayerState();
        state.setUserId("u1");
        state.setRepeatMode(RepeatMode.OFF);
        repository.savePlayerState(state);

        assertEquals(RepeatMode.ALL,
                playerService.applyCommand(buildCommand("u1", PlayerCommand.REPEAT_TOGGLE)).getRepeatMode());
        assertEquals(RepeatMode.ONE,
                playerService.applyCommand(buildCommand("u1", PlayerCommand.REPEAT_TOGGLE)).getRepeatMode());
        assertEquals(RepeatMode.OFF,
                playerService.applyCommand(buildCommand("u1", PlayerCommand.REPEAT_TOGGLE)).getRepeatMode());
    }

    // ── applyCommand: MUTE ──────────────────────────────────────────────────────

    @Test
    void applyCommand_muteCommand_togglesMute() {
        PlayerState state = new PlayerState();
        state.setUserId("u1");
        state.setMute(false);
        repository.savePlayerState(state);

        PlayerState result = playerService.applyCommand(buildCommand("u1", PlayerCommand.MUTE));
        assertTrue(result.getMute());

        result = playerService.applyCommand(buildCommand("u1", PlayerCommand.MUTE));
        assertFalse(result.getMute());
    }

    // ── helpers ─────────────────────────────────────────────────────────────────

    private PlayerCommandDTO buildCommand(String userId, PlayerCommand command) {
        PlayerCommandDTO dto = new PlayerCommandDTO();
        dto.setUserId(userId);
        dto.setCommand(command);
        return dto;
    }

    private PlayerState buildStateWithTracks(String userId, int trackCount) {
        PlayerState state = new PlayerState();
        state.setUserId(userId);
        state.setStatus(PlayerStatus.PAUSED);
        state.setRepeatMode(RepeatMode.OFF);
        state.setShuffle(false);
        List<String> trackIds = new ArrayList<>();
        for (int i = 0; i < trackCount; i++) {
            trackIds.add("track" + i);
        }
        state.setTrackIds(trackIds);
        state.setCurrentTrackIndex(0);
        state.setPosition(0);
        state.setDuration(200);
        return state;
    }
}

